### ISSUE TITLE
How to extract-reward-tokens

### ISSUE THREAD

**Issue by TheStophe** [reqlez/tn-ergo-easy-oracle#3]
According to the ergo-oracle there's a extract-reward-tokens command: https://github.com/ergoplatform/oracle-core#extract-reward-tokens

What would be the proper 'docker' way to run this command? From what directory? Maybe a wiki to how-to guide would be helpful for some everyday operations?

**Comment by TheStophe** [comment]
Do I need these lines uncommented in the docker-compose.yml file to be able to run a `./oracle-core extract-reward-tokens <ADDRESS>`?

```
  core:
    #build:
    #  context: ./oracle-core # Path to oracle-core repo
    #  dockerfile: ../oracle.Dockerfile # Relative to oracle-core repo
    #  args:
    #    CCARCH: x86_64  # Change if different arch, options: x86_64 or aarch64
```

https://github.com/reqlez/ergo-easy-oracle/blob/38716420a91cabb103118fc47f80b540cd35f050/docker-compose.yml#L28C1-L33C80

**Comment by reqlez** [comment]
Going to post a comment by QX from Operators chat:

"For those of you using docker or any access to the shell not in docker, the only luck I had when extracting tokens using boris' docker is:

`docker ps`

get the container id of oracle-core, it looks something like this: f5844374cf34

`docker exec -ti CONTAINER_ID_FROM_PREVIOUS_STEP /bin/sh`

`cd /data`

cd's into the data directory

`oracle-core extract-reward-tokens YOUR_destination_WALLET_address`

executes the extract command"

**Comment by TheStophe** [comment]
Oh wow, that worked! Would have never guessed the /data file was from a specific container! Thank you! 

If you want I can edit and make a section for this in your tutorial?

**Comment by reqlez** [comment]
> Oh wow, that worked! Would have never guessed the /data file was from a specific container! Thank you!
> 
> If you want I can edit and make a section for this in your tutorial?

i need to test, because this is not the normal way. After i test i will add documentation about this.
