### ISSUE TITLE
Oracle core bad Explorer error for ergo-explorer.tosidrop.io

### ISSUE THREAD

**Issue by TheStophe** [reqlez/tn-ergo-easy-oracle#4]
I cannot send txns out of Satergo from the oracle wallet full node (ref: https://github.com/Satergo/Satergo/issues/21)

Upon investigation, and voting to upgrade the oracle contract to v2.0, I noticed the following error. Is there a way to update the ` oracle_config.yaml` to have https://ergexplorer.com/ instead? Assuming this is the issue.

`2023-11-16T02:00:07.655197262+00:00 DEBUG oracle_core::explorer_api - ExplorerApi error: reqwest error: HTTP status server error (502 Bad Gateway) for url (https://ergo-explorer.tosidrop.io/api/v1/transactions/655cb90dba787d999a07c69c31417d25baa282422436ea17223772dd88195877)
`

Here's the working transaction from the explorer: https://ergexplorer.com/transactions#655cb90dba787d999a07c69c31417d25baa282422436ea17223772dd88195877

**Comment by reqlez** [comment]
Sorry, i'm going to update the default explorer. I killed the last one...

**Comment by reqlez** [comment]
Actually, this was changed 2 months ago in this commit:

https://github.com/reqlez/ergo-easy-oracle/commit/5ce47405ce89c9b4188623dd96bf8edb2fb1426
